import { useState } from 'react'
import { Pressable, SafeAreaView, Text, View } from 'react-native'
import * as ImagePicker from 'expo-image-picker'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { useStore } from '@/lib/store'
import type { SessionOutcome } from '@/lib/types'
import { colors, styles } from '@/lib/theme'
export default function Complete() {
  const { title = 'Focus session', minutes = '25', elapsed = minutes } = useLocalSearchParams<{ title?: string; minutes?: string; elapsed?: string }>(); const [outcome, setOutcome] = useState<SessionOutcome>('completed'); const [proofUri, setProofUri] = useState<string>(); const { saveSession } = useStore(); const router = useRouter()
  async function addProof() { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.7 }); if (!result.canceled) setProofUri(result.assets[0].uri) }
  function save() { saveSession({ id: Date.now().toString(), taskTitle: String(title), minutes: Number(elapsed), outcome, proofUri, createdAt: new Date().toISOString() }); router.replace('/') }
  return <SafeAreaView style={styles.screen}><View style={[styles.content, { flex: 1, justifyContent: 'center' }]}><View style={{ alignItems: 'center' }}><View style={{ width: 58, height: 58, borderRadius: 29, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 26, color: colors.forest }}>✓</Text></View><Text style={styles.eyebrow}>FOCUS COMPLETE</Text><Text style={[styles.title, { textAlign: 'center', marginTop: 12 }]}>You showed up.</Text><Text style={[styles.subtitle, { textAlign: 'center', marginTop: 10 }]}>That counts. Notice what you made space for.</Text></View><View style={[styles.card, { padding: 18, marginTop: 30 }]}><Text style={{ fontWeight: '700', color: colors.ink }}>{title}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 6 }}>{elapsed} minutes focused</Text></View><Text style={[styles.eyebrow, { marginTop: 30, marginBottom: 12 }]}>HOW DID IT GO?</Text>{(['completed', 'partial', 'not_completed'] as SessionOutcome[]).map((item) => <Pressable key={item} onPress={() => setOutcome(item)} style={[styles.card, styles.row, { padding: 15, marginBottom: 8, borderColor: outcome === item ? colors.lime : colors.line }]}><View style={{ width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: colors.line, backgroundColor: outcome === item ? colors.lime : 'transparent' }} /><Text style={{ marginLeft: 12, color: colors.ink }}>{item === 'completed' ? 'Goal completed' : item === 'partial' ? 'Partially completed' : 'Not completed'}</Text></Pressable>)}<Pressable onPress={addProof} style={{ paddingVertical: 16 }}><Text style={{ color: colors.muted, textAlign: 'center', fontSize: 12 }}>{proofUri ? '✓ Proof of progress attached' : '+ Add optional Proof of Progress photo'}</Text></Pressable><Pressable style={styles.button} onPress={save}><Text style={styles.buttonText}>SAVE SESSION</Text><Text style={{ color: '#FFF' }}>→</Text></Pressable></View></SafeAreaView>
}
