import { useEffect, useMemo, useState } from 'react'
import { Alert, Pressable, SafeAreaView, Text, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { colors, styles } from '@/lib/theme'
export default function Focus() {
  const { title = 'Focus session', goal = '', minutes = '25' } = useLocalSearchParams<{ title?: string; goal?: string; minutes?: string }>(); const router = useRouter(); const total = Number(minutes) * 60; const [seconds, setSeconds] = useState(total); const [running, setRunning] = useState(true)
  useEffect(() => { if (!running || seconds <= 0) return; const timer = setInterval(() => setSeconds((value) => value - 1), 1000); return () => clearInterval(timer) }, [running, seconds])
  const display = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; const progress = Math.round(((total - seconds) / total) * 100)
  function end() { Alert.alert('End this session?', 'You have already invested time in yourself. Your progress will be saved as incomplete.', [{ text: 'Keep going', style: 'cancel' }, { text: 'End session', style: 'destructive', onPress: () => router.replace({ pathname: '/complete', params: { title, minutes: String(minutes), elapsed: String(Math.max(0, Math.floor((total - seconds) / 60))) } }) }]) }
  return <SafeAreaView style={[styles.screen, { backgroundColor: '#EEF1E8' }]}><View style={{ flex: 1, padding: 24, justifyContent: 'space-between' }}><View style={[styles.row, { justifyContent: 'space-between' }]}><Text style={styles.brand}>LOCKIN<Text style={{ color: colors.lime }}>•</Text></Text><Pressable onPress={end}><Text style={{ color: colors.muted }}>Exit ×</Text></Pressable></View><View style={{ alignItems: 'center' }}><View style={{ borderWidth: 2, borderColor: colors.lime, width: 250, height: 250, borderRadius: 125, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 47, fontWeight: '700', color: colors.ink }}>{display}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>remaining</Text></View><Text style={[styles.eyebrow, { marginTop: 38 }]}>● IN FOCUS · {progress}% COMPLETE</Text><Text style={{ color: colors.ink, fontSize: 30, fontWeight: '500', textAlign: 'center', marginTop: 13 }}>{title}</Text>{goal ? <Text style={[styles.subtitle, { textAlign: 'center', marginTop: 10 }]}>{goal}</Text> : null}<Pressable style={[styles.button, { marginTop: 30, minWidth: 180 }]} onPress={() => seconds === 0 ? router.replace({ pathname: '/complete', params: { title, minutes: String(minutes), elapsed: String(minutes) } }) : setRunning((value) => !value)}><Text style={styles.buttonText}>{seconds === 0 ? 'Complete focus' : running ? 'Pause session' : 'Resume session'}</Text><Text style={{ color: '#FFF' }}>{running ? 'Ⅱ' : '▶'}</Text></Pressable></View><View style={[styles.row, { justifyContent: 'space-between', borderTopWidth: 1, borderColor: colors.line, paddingTop: 18 }]}><Text style={{ color: colors.muted, fontSize: 11 }}>◉ Protected by LOCKIN</Text><Text style={{ color: colors.muted, fontSize: 11 }}>Blocking preferences saved</Text></View></View></SafeAreaView>
}
