import { ScrollView, Text, View } from 'react-native'
import { Navigation } from '@/components/Navigation'
import { Header } from '@/components/Header'
import { useStore } from '@/lib/store'
import { colors, styles } from '@/lib/theme'
export default function Progress() {
  const { data } = useStore(); const minutes = data.sessions.reduce((sum, session) => sum + session.minutes, 0); const completed = data.sessions.filter((session) => session.outcome === 'completed').length
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Header eyebrow="YOUR MOMENTUM" title="Progress that feels like you." subtitle="Consistency over intensity. Look how far you’ve come." /><View style={[styles.row, { gap: 9 }]}>{[[minutes, 'focused minutes'], [completed, 'goals completed'], [data.streak, 'day streak']].map(([value, label]) => <View key={String(label)} style={[styles.card, { flex: 1, padding: 15 }]}><Text style={{ fontSize: 25, fontWeight: '700', color: colors.ink }}>{value}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 8 }}>{label}</Text></View>)}</View><View style={[styles.card, { padding: 20, marginTop: 16 }]}><Text style={styles.eyebrow}>FOCUS HISTORY</Text><Text style={{ color: colors.ink, fontSize: 22, fontWeight: '500', marginTop: 8 }}>Your recent sessions</Text>{data.sessions.length === 0 ? <Text style={[styles.subtitle, { marginTop: 20 }]}>Complete your first session to start building your history.</Text> : data.sessions.slice(0, 8).map((session) => <View key={session.id} style={[styles.row, { borderTopWidth: 1, borderColor: colors.line, paddingVertical: 14, marginTop: 14 }]}><View style={{ flex: 1 }}><Text style={{ fontWeight: '600', color: colors.ink }}>{session.taskTitle}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 4 }}>{session.minutes} min · {session.outcome.replace('_', ' ')}</Text></View><Text style={{ color: colors.lime, fontSize: 20 }}>●</Text></View>)}</View><View style={{ marginTop: 16, padding: 20, backgroundColor: colors.pale }}><Text style={styles.eyebrow}>A NOTE FROM YOUR DATA</Text><Text style={{ fontSize: 21, fontWeight: '500', color: colors.ink, marginTop: 8 }}>You focus best in the morning.</Text><Text style={[styles.subtitle, { marginTop: 8 }]}>Protect your clearest window for the work that matters most.</Text></View></ScrollView><Navigation /></View>
}app/progress.tsx
