import { useState } from 'react'
import { Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native'
import { useStore } from '@/lib/store'
import { colors, styles } from '@/lib/theme'
const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
export default function Schedule() {
  const { data, setPreferences } = useStore(); const [course, setCourse] = useState(''); const [day, setDay] = useState('Monday'); const [start, setStart] = useState('9:00 AM'); const [end, setEnd] = useState('10:00 AM'); const [location, setLocation] = useState('')
  function add() { if (!course.trim()) return; setPreferences({ schedule: [...data.schedule, { id: Date.now().toString(), course: course.trim(), day, start, end, location }] }); setCourse(''); setLocation('') }
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>YOUR SCHOOL SCHEDULE</Text><Text style={styles.title}>Build your week.</Text><Text style={[styles.subtitle, { marginTop: 10 }]}>Add as many classes as you need. Your schedule stays on this device.</Text><View style={[styles.card, { padding: 17, marginTop: 24 }]}><Text style={styles.eyebrow}>ADD CLASS</Text><TextInput value={course} onChangeText={setCourse} placeholder="Class or activity" placeholderTextColor="#98A095" style={{ borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, color: colors.ink }} /><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginTop: 14 }}>{days.map((item) => <Pressable key={item} onPress={() => setDay(item)} style={{ padding: 10, marginRight: 7, borderRadius: 18, backgroundColor: day === item ? colors.pale : colors.card, borderWidth: 1, borderColor: day === item ? colors.lime : colors.line }}><Text style={{ fontSize: 11, color: colors.ink }}>{item.slice(0, 3)}</Text></Pressable>)}</ScrollView><View style={[styles.row, { gap: 10, marginTop: 12 }]}><TextInput value={start} onChangeText={setStart} placeholder="Start" placeholderTextColor="#98A095" style={{ flex: 1, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, color: colors.ink }} /><TextInput value={end} onChangeText={setEnd} placeholder="End" placeholderTextColor="#98A095" style={{ flex: 1, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, color: colors.ink }} /></View><TextInput value={location} onChangeText={setLocation} placeholder="Room or location (optional)" placeholderTextColor="#98A095" style={{ borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, color: colors.ink, marginTop: 8 }} /><Pressable style={[styles.button, { marginTop: 18 }]} onPress={add}><Text style={styles.buttonText}>+ ADD TO SCHEDULE</Text></Pressable></View>{days.map((item) => { const entries = data.schedule.filter((entry) => entry.day === item); return entries.length ? <View key={item} style={{ marginTop: 25 }}><Text style={styles.eyebrow}>{item.toUpperCase()}</Text>{entries.map((entry) => <View key={entry.id} style={[styles.card, { padding: 15, marginTop: 8 }]}><Text style={{ fontWeight: '700', color: colors.ink }}>{entry.course}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 5 }}>{entry.start} – {entry.end}{entry.location ? ` · ${entry.location}` : ''}</Text></View>)}</View> : null })}</ScrollView></SafeAreaView>
}
