import { useState } from 'react'
import { Pressable, SafeAreaView, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'
import { useStore } from '@/lib/store'
import { colors, styles } from '@/lib/theme'
export default function Onboarding() {
  const [step, setStep] = useState(0); const [intention, setIntention] = useState(''); const { finishOnboarding } = useStore(); const router = useRouter()
  const slides = [{ kicker: 'WELCOME TO LOCKIN', title: 'Your attention is yours again.', body: 'A calmer way to get meaningful work done. No guilt. Just a little more room to focus.' }, { kicker: 'HOW IT WORKS', title: 'Choose one thing. We protect the time.', body: 'LOCKIN makes distraction harder and starting easier with thoughtful focus sessions.' }, { kicker: 'A SMALL PROMISE', title: 'What would you like to make space for?', body: 'Start with one intention. You can always change it later.' }]
  const slide = slides[step]
  return <SafeAreaView style={styles.screen}><View style={[styles.content, { flex: 1, justifyContent: 'space-between', paddingTop: 25 }]}><Text style={styles.brand}>LOCKIN<Text style={{ color: colors.lime }}>•</Text></Text><View style={{ alignItems: 'center', marginTop: 70 }}><View style={{ width: 170, height: 170, borderRadius: 85, borderWidth: 1, borderColor: '#B6C2AD', alignItems: 'center', justifyContent: 'center', marginBottom: 45 }}><Text style={{ fontSize: 24, fontStyle: 'italic', color: colors.ink }}>{step === 0 ? 'focus' : step === 1 ? '25:00' : 'space'}</Text></View><Text style={styles.eyebrow}>{slide.kicker}</Text><Text style={[styles.title, { textAlign: 'center', fontSize: 42 }]}>{slide.title}</Text><Text style={[styles.subtitle, { textAlign: 'center', marginTop: 16 }]}>{slide.body}</Text>{step === 2 && <TextInput value={intention} onChangeText={setIntention} placeholder="e.g. finish my essay" placeholderTextColor="#A0A99B" style={{ borderBottomWidth: 1, borderColor: '#B7C1B2', width: '85%', paddingVertical: 12, textAlign: 'center', marginTop: 28, color: colors.ink }} />}</View><View><View style={[styles.row, { gap: 5, marginBottom: 22 }]}>{slides.map((_, i) => <View key={i} style={{ height: 3, width: i === step ? 32 : 17, backgroundColor: i === step ? colors.ink : colors.line }} />)}</View><Pressable style={styles.button} onPress={() => step < 2 ? setStep(step + 1) : (finishOnboarding(intention), router.replace('/'))}><Text style={styles.buttonText}>{step < 2 ? 'Continue' : "Let's begin"}</Text><Text style={{ color: '#FFF', fontSize: 18 }}>→</Text></Pressable></View></View></SafeAreaView>
}
