import { useState } from 'react'
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { Header } from '@/components/Header'
import { useStore } from '@/lib/store'
import { colors, styles } from '@/lib/theme'
export default function CreateSession() {
  const { taskId } = useLocalSearchParams<{ taskId?: string }>(); const { data } = useStore(); const router = useRouter(); const task = data.tasks.find((item) => item.id === taskId); const [title, setTitle] = useState(task?.title ?? ''); const [goal, setGoal] = useState(''); const [minutes, setMinutes] = useState(task?.minutes ?? data.defaultMinutes); const [blocked, setBlocked] = useState<string[]>(data.blockedApps)
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header eyebrow="CREATE FOCUS SESSION" title="Protect the next step." subtitle="Choose a task, set a clear goal, and make the time yours." /><Text style={styles.eyebrow}>TASK</Text><TextInput value={title} onChangeText={setTitle} placeholder="What are you working on?" placeholderTextColor="#98A095" style={{ borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 13, color: colors.ink, fontSize: 16 }} /><Text style={[styles.eyebrow, { marginTop: 28 }]}>SPECIFIC GOAL</Text><TextInput value={goal} onChangeText={setGoal} placeholder="e.g. finish the first two pages" placeholderTextColor="#98A095" style={{ borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 13, color: colors.ink, fontSize: 16 }} /><Text style={[styles.eyebrow, { marginTop: 28, marginBottom: 12 }]}>FOCUS DURATION</Text><View style={[styles.row, { gap: 8 }]}>{[25, 45, 60].map((option) => <Pressable key={option} onPress={() => setMinutes(option)} style={{ flex: 1, padding: 15, borderWidth: 1, borderColor: minutes === option ? colors.ink : colors.line, backgroundColor: minutes === option ? colors.pale : colors.card, alignItems: 'center' }}><Text style={{ color: colors.ink, fontWeight: '600' }}>{option} min</Text></Pressable>)}</View><Text style={[styles.eyebrow, { marginTop: 28, marginBottom: 12 }]}>DISTRACTIONS TO BLOCK LATER</Text><Text style={{ color: colors.muted, fontSize: 12, marginBottom: 12 }}>This saves your preferences for a future native blocking module. LOCKIN does not block apps yet.</Text><View style={[styles.row, { flexWrap: 'wrap', gap: 8 }]}>{data.blockedApps.map((app) => <Pressable key={app} onPress={() => setBlocked((current) => current.includes(app) ? current.filter((item) => item !== app) : [...current, app])} style={{ borderWidth: 1, borderColor: blocked.includes(app) ? colors.lime : colors.line, backgroundColor: blocked.includes(app) ? colors.pale : colors.card, padding: 11, borderRadius: 20 }}><Text style={{ color: colors.ink, fontSize: 12 }}>{blocked.includes(app) ? '✓ ' : ''}{app}</Text></Pressable>)}</View><Pressable style={[styles.button, { marginTop: 35, marginBottom: 25 }]} onPress={() => router.push({ pathname: '/focus', params: { title: title || 'Focus session', goal, minutes: String(minutes) } })}><Text style={styles.buttonText}>START LOCKIN</Text><Text style={{ color: '#FFF', fontSize: 18 }}>→</Text></Pressable></ScrollView>
}
