import { Redirect, useRouter } from 'expo-router'
import { Pressable, ScrollView, Text, View } from 'react-native'
import { Navigation } from '@/components/Navigation'
import { useStore } from '@/lib/store'
import { colors, styles } from '@/lib/theme'
export default function Home() {
  const { data, loading } = useStore(); const router = useRouter()
  if (loading) return null
  if (!data.onboarded) return <Redirect href="/onboarding" />
  const next = data.tasks.find((task) => !task.done); const done = data.tasks.filter((task) => task.done).length
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content}><View style={[styles.row, { justifyContent: 'space-between', marginBottom: 44 }]}><Text style={styles.brand}>LOCKIN<Text style={{ color: colors.lime }}>•</Text></Text><Text style={{ color: colors.muted, fontSize: 12 }}>● Focus mode ready</Text></View>
    <Text style={styles.eyebrow}>THURSDAY, SEPTEMBER 10</Text><Text style={styles.title}>Good morning, Annalise.</Text><Text style={[styles.subtitle, { marginTop: 8 }]}>A little progress is still progress. What feels most important today?</Text>
    <View style={{ backgroundColor: colors.forest, padding: 24, borderRadius: 5, marginTop: 30 }}><Text style={[styles.eyebrow, { color: colors.cream }]}>YOUR NEXT FOCUS</Text><Text style={{ color: '#FFF', fontSize: 27, fontWeight: '500', marginTop: 20 }}>{next?.title ?? 'You cleared your queue.'}</Text><Text style={{ color: '#B6C4B5', marginTop: 8 }}>{next ? `${next.course} · ${next.minutes} min` : 'Take a breath and enjoy the space you made.'}</Text><Pressable onPress={() => next && router.push({ pathname: '/create', params: { taskId: next.id } })} style={[styles.button, { backgroundColor: colors.cream, marginTop: 25 }]}><Text style={{ color: colors.forest, fontWeight: '700' }}>LOCK IN</Text><Text style={{ color: colors.forest, fontSize: 18 }}>→</Text></Pressable></View>
    <View style={[styles.row, { justifyContent: 'space-between', marginTop: 36, marginBottom: 14 }]}><View><Text style={styles.eyebrow}>TODAY'S QUEUE</Text><Text style={{ fontSize: 23, fontWeight: '500', color: colors.ink, marginTop: 7 }}>Make it manageable.</Text></View><Pressable onPress={() => router.push('/tasks')}><Text style={{ color: colors.muted, fontSize: 12 }}>View all →</Text></Pressable></View>
    {data.tasks.slice(0, 3).map((task) => <View key={task.id} style={[styles.card, styles.row, { padding: 16, marginBottom: 8 }]}><View style={{ width: 20, height: 20, borderRadius: 10, borderWidth: 1, borderColor: task.done ? colors.lime : '#AEB6A8', backgroundColor: task.done ? colors.lime : 'transparent', alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontSize: 11 }}>{task.done ? '✓' : ''}</Text></View><View style={{ flex: 1, marginLeft: 12 }}><Text style={{ color: colors.ink, fontWeight: '600', textDecorationLine: task.done ? 'line-through' : 'none' }}>{task.title}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 5 }}>{task.course} · {task.minutes} min</Text></View>{!task.done && <Pressable onPress={() => router.push({ pathname: '/create', params: { taskId: task.id } })}><Text style={{ color: colors.muted, fontSize: 12 }}>Start →</Text></Pressable>}</View>)}
    <View style={[styles.row, { gap: 10, marginTop: 28 }]}><View style={[styles.card, { flex: 1, padding: 18 }]}><Text style={styles.eyebrow}>TODAY</Text><Text style={{ fontSize: 26, fontWeight: '700', marginTop: 14 }}>{done}/{data.tasks.length}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>goals completed</Text></View><View style={[styles.card, { flex: 1, padding: 18 }]}><Text style={styles.eyebrow}>STREAK</Text><Text style={{ fontSize: 26, fontWeight: '700', marginTop: 14 }}>{data.streak}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>days showing up</Text></View></View>
  </ScrollView><Navigation /></View>
}
