import { useState } from 'react'
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'
import { Navigation } from '@/components/Navigation'
import { Header } from '@/components/Header'
import { useStore } from '@/lib/store'
import { colors, styles } from '@/lib/theme'
export default function Tasks() {
  const { data, addTask, toggleTask } = useStore(); const router = useRouter(); const [adding, setAdding] = useState(false); const [title, setTitle] = useState('')
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Header eyebrow="YOUR TASKS" title="Make it manageable." subtitle="Today's work, in one calm place." /><Pressable style={[styles.button, { marginBottom: 22 }]} onPress={() => setAdding(true)}><Text style={styles.buttonText}>+ Add task</Text></Pressable>{adding && <View style={[styles.card, { padding: 16, marginBottom: 18 }]}><TextInput value={title} onChangeText={setTitle} autoFocus placeholder="What needs your attention?" placeholderTextColor="#98A095" style={{ borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, color: colors.ink }} /><Pressable style={[styles.button, { marginTop: 15 }]} onPress={() => { if (title.trim()) addTask({ title: title.trim(), course: 'Personal', minutes: data.defaultMinutes, priority: 'Medium' }); setTitle(''); setAdding(false) }}><Text style={styles.buttonText}>Add to queue</Text></Pressable></View>}{data.tasks.map((task) => <View key={task.id} style={[styles.card, styles.row, { padding: 16, marginBottom: 9 }]}><Pressable onPress={() => toggleTask(task.id)} style={{ width: 22, height: 22, borderRadius: 11, borderWidth: 1, borderColor: task.done ? colors.lime : '#AEB6A8', backgroundColor: task.done ? colors.lime : 'transparent', alignItems: 'center', justifyContent: 'center' }}><Text>{task.done ? '✓' : ''}</Text></Pressable><View style={{ flex: 1, marginLeft: 13 }}><Text style={{ fontWeight: '600', color: colors.ink, textDecorationLine: task.done ? 'line-through' : 'none' }}>{task.title}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 5 }}>{task.course} · {task.minutes} min</Text></View>{!task.done && <Pressable onPress={() => router.push({ pathname: '/create', params: { taskId: task.id } })}><Text style={{ color: colors.muted, fontSize: 12 }}>LOCK IN →</Text></Pressable>}</View>)}</ScrollView><Navigation /></View>
}
