import { useState } from 'react'
import { Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import { useStore } from '@/lib/store'
import type { StopReason } from '@/lib/types'
import { colors, styles } from '@/lib/theme'
const reasons: StopReason[] = ['Finished early', 'Assignment took longer than expected', 'Got distracted', 'Didn’t understand the material', 'Something came up', 'Other']
export default function StopSession() {
  const params = useLocalSearchParams<{ title?: string; goal?: string; minutes?: string; elapsed?: string }>()
  const [reason, setReason] = useState<StopReason>('Finished early'); const [other, setOther] = useState(''); const router = useRouter(); const { saveSession } = useStore()
  function endSession() { saveSession({ id: Date.now().toString(), taskTitle: String(params.title || 'Focus session'), minutes: Number(params.elapsed || 0), outcome: 'not_completed', stopReason: reason, createdAt: new Date().toISOString() }); router.replace('/') }
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={[styles.content, { flexGrow: 1, justifyContent: 'center' }]}><Text style={styles.eyebrow}>EMERGENCY CANCEL</Text><Text style={[styles.title, { marginTop: 10 }]}>End session?</Text><Text style={[styles.subtitle, { marginTop: 10 }]}>You still have {Math.max(0, Number(params.minutes || 25) - Math.floor(Number(params.elapsed || 0)))} minutes left.</Text><View style={[styles.card, { padding: 18, marginTop: 24 }]}><Text style={styles.eyebrow}>YOUR GOAL WAS</Text><Text style={{ color: colors.ink, fontSize: 18, fontWeight: '600', marginTop: 10 }}>{params.goal || params.title || 'Stay focused'}</Text></View><Text style={[styles.eyebrow, { marginTop: 30, marginBottom: 12 }]}>WHY DID YOU STOP?</Text>{reasons.map((item) => <Pressable key={item} onPress={() => setReason(item)} style={[styles.card, styles.row, { padding: 14, marginBottom: 8, borderColor: reason === item ? colors.lime : colors.line }]}><View style={{ width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: colors.line, backgroundColor: reason === item ? colors.lime : 'transparent' }} /><Text style={{ color: colors.ink, marginLeft: 12, flex: 1 }}>{item}</Text></Pressable>)}{reason === 'Other' && <TextInput value={other} onChangeText={setOther} placeholder="Tell us what came up" placeholderTextColor="#98A095" style={{ borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, color: colors.ink }} />}<Pressable style={[styles.button, { marginTop: 22 }]} onPress={() => router.back()}><Text style={styles.buttonText}>CONTINUE SESSION</Text></Pressable><Pressable style={{ padding: 17 }} onPress={endSession}><Text style={{ color: '#976557', textAlign: 'center', fontWeight: '700' }}>END SESSION</Text></Pressable></ScrollView></SafeAreaView>
}
